{{- if .Values.ingress }}
{{- if (eq .Values.ingress.enable true) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  {{- if .Values.ingress.tls }}
  {{- if (eq .Values.ingress.tls.enable true) }}
  tls:
    - hosts: 
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        {{- range .Values.ingress.paths }}
        - backend:
            service:
              name: {{ .Values.appName }}
              port:
                number: {{ .port }}
          path: {{ .path }}
          pathType: {{ .pathType | default "Prefix" }}
        {{- end }}
{{- end }}
---
{{- if (eq .Values.ingress.middleware_strip_prefix.enable true) }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: "{{ .Values.ingress.name }}-{{ .Values.appName }}-strip-prefix"
  namespace: {{ .Values.namespace }}
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      {{- range .Values.ingress.paths }}
      - {{ .path }}
      {{- end }}
{{- end }}
---
{{- if (eq .Values.ingress.middleware_validate_header.enable true) }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: "{{ .Values.ingress.name }}-{{ .Values.appName }}-validate-headers"
  namespace: {{ .Values.namespace }}
spec:
  plugin:
    traefik-plugin-validate-headers:
      headers:
        - header:
          name: "Authorization"
          matchtype: one
          values:
            - "^Bearer .*"
          regex: true
{{- end }}
{{- end }}