{{- if .Values.secret }}
{{- if (eq .Values.secret.enable true) }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.appName }}-secret"
  namespace: {{ .Values.namespace }}
type: Opaque
data:
{{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- end }}